version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: always

  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/volume/var/lib/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - clickhouse
    depends_on:
      - clickhouse
    restart: always